name: emat
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bokeh=2.3.3
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - click=8.0.1
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.8.1
  - dask-core=2021.8.1
  - datashader=0.13.0
  - datashape=0.5.4
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - dill=0.3.4
  - distributed=2021.8.1
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - fsspec=2021.8.1
  - git=2.32.0
  - graphviz=2.38
  - greenlet=1.1.1
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - iniconfig=1.1.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipyparallel=6.3.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.4
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kaleido-core=0.2.1
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - llvmlite=0.36.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - mathjax=2.7.7
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - more-itertools=8.8.0
  - msgpack-python=1.0.2
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - multiprocess=0.70.12.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandocfilters=1.4.3
  - param=1.11.1
  - parso=0.8.2
  - partd=1.2.0
  - pathos=0.2.8
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - platypus-opt=1.0.4
  - plotly=5.1.0
  - pluggy=0.13.1
  - pox=0.3.0
  - ppft=1.6.6.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - psutil=5.8.0
  - py=1.10.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydot=1.4.1
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-kaleido=0.2.1
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=228
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.10.0
  - requests=2.26.0
  - salib=1.4.5
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.15.0
  - sortedcontainers=2.4.0
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tbb=2020.3
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.1.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.19.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - git+https://github.com/tmip-emat/tmip-emat@v0.5.3
    - et-xmlfile==1.1.0
    - openpyxl==3.0.10
