library(visioneval)
ematmodel <- openModel(getwd())
qry <- ematmodel$query("Policy-Output.VEqry")
qry$run(Force=TRUE)
output_path <- file.path(ematmodel$setting("ModelDir"), ematmodel$setting("ResultsDir"), ematmodel$setting("OutputDir"))
unlink(output_path, recursive=TRUE)
qry$export()
output_file <- list.files(path=output_path, pattern ="Policy-Output", recursive=TRUE, full.names=TRUE)
file.copy(output_file, file.path(output_path, "pricing_output.csv"))
