model_archive: ./VisionEval-Archive
model_type: VE-State
model_variant: odot-otp
# Future year to run the scenarios on
model_year: 2050
# Base model to be loaded to run future year
base_year: 2010
base_model: C:/Users/aditya.gore/Projects/OregScenPlanning_VE/GitHub/VisionEval-Dev/built/visioneval/4.2.3/runtime/models/VE-State-odot-otp
# Model results extraction script
extract_script: extract_outputs.R

rel_output_path: results/output
# Path to VE library that should be used to run the VE model
r_library_path: C:/Users/aditya.gore/Projects/OregScenPlanning_VE/GitHub/VisionEval-Dev/built/visioneval/4.2.3/ve-lib
# Path to VE runtime environment which will give the wrapper access to the different VEModel tools
r_runtime_path: C:/Users/aditya.gore/Projects/OregScenPlanning_VE/GitHub/VisionEval-Dev/built/visioneval/4.2.3/runtime
# R executable that should be used to run particular VE model. Ensure that the VE library and runtime environment matches with the version of R executable specified here.
r_executable: C:/Program Files/R/R-4.2.3/bin


# Mandatory field but not used by the model
model_path: .
